%YAML 1.1
---
version: '>0.9.0 || @head'
export: |

    project "GLFW"
        kind "StaticLib"

        files {
            "src/context.c",
            "src/init.c",
            "src/input.c",
            "src/monitor.c",
            "src/vulkan.c",
            "src/window.c",
            "src/osmesa_context.c"
        }

        filter "system:windows"

            files {
                "src/win32_*",
                "src/wgl_context.c",
                "src/egl_context.c"
            }

        filter "system:linux"

            files {
                "src/x11_*",
                "src/linux_*",
                "src/xkb_unicode.c",
                "src/posix_time.c",
                "src/posix_thread.c",
                "src/glx_context.c",
                "src/egl_context.c"
            }

        filter "system:macosx"

            files {
                "src/cocoa_*",
                "src/xkb_unicode.c",
                "src/posix_thread.c",
                "src/nsgl_context.m",
                "src/egl_context.c"
            }

        filter {}

        zpm.export [[
            includedirs "include"
            cppdialect "C++11"


            filter "system:windows"

                defines "_GLFW_WIN32"

            filter "system:linux"

                defines "_GLFW_X11"

                links {
                    "pthread",
                    "Xrandr",
                    "X11",
                    "Xi",
                    "dl"
                }

            filter "system:macosx"

                defines "_GLFW_COCOA"

                linkoptions "-ObjC -framework CoreFoundation -framework CoreVideo -framework IOKit -framework Cocoa"

            filter {}
        ]]
...